### PR TITLE
improvements

### PR DESCRIPTION
**Pull request by aaron-kaplan**
Various playbook improvements that I made while writing the documentation. The most significant is the option to run ansible in the VM rather than on the host, since that's the way I'm going to suggest partners do it.

So nobody gets confused, the previous [PR](https://bitbucket.org/iridl/iridl-ansible/pull-requests/1) was on bitbucket.

### CODE REVIEW

**Comment by aaron-kaplan** [comment]
@kgraaf please review. For the most part each commit is self-contained and independent of the others, so I suggest reading it one commit at a time.

The only further change I'm currently planning is to try setting up CI with GitHub Actions.

**Comment by jturmelle** [comment]
I think that SMTP relay is not the correct mechanism for remote data library sites.  I added this to our site because I wanted to centralize our internal emails delivering to google.  Most sites will probably not have this capability and will want us to configure their mail delivery directly to the internet.  The default postfix configuration should work for this,  as long as its enabled.  I'd also disable incoming SMTP to prevent inadvertently becoming an open mail relay.  Do you want me to try and configure this by pushing changes to this branch or just tell you how to do it?

**Comment by aaron-kaplan** [comment]
@jturmelle thanks for that comment. But if we just attempt direct delivery, aren't we likely to have delivery problems? I was under the impression that to get email delivered these days you need to set up DKIM, SPF, and also be Google, or else many sites will just reject your email as probable spam. Do existing partner sites send any email? Maybe we should just deliver to root@localhost instead of trying to send externally.

**Comment by jturmelle** [comment]
Good point, you're probably right.  I suppose we could also configure their sites to use our gmail account as an SMTP relay, as we do.  My concern about doing this would be Google eventually blocks us for spam.  I agree just configuring mail to deliver locally will be the easiest as a default option.  Maybe not to root, but to a DL administrator configured on the server?

**Comment by aaron-kaplan** [comment]
@jturmelle I pushed a commit that makes mail_relay optional. Does this look good?

**Comment by aaron-kaplan** [comment]
Any other chnages that need to happen in the postfix config file if we're not using a mail relay?

**Comment by jturmelle** [comment]
Everything looks correct to me.

**Comment by kgraaf** [comment]
As we discussed over zoom yesterday, everything looks good to me. Something I did want to note for posterity lest we forget: in the test script, sub-commands are "parsed" and then dispatched sequentially which has the unintended but desirable side effect of allowing the user to change the execution mode multiple times and in between sub-command execution. @aaron-kaplan and I decided this behavior is worthwhile.

**Comment by aaron-kaplan** [comment]
@kgraaf you haven't clicked the approve button. It's on the "Files changed" tab.

**Comment by aaron-kaplan** [comment]
Sorry, the button is actually called "review changes."

**Comment by aaron-kaplan** [comment]
Maybe you did approve? "Review requested" has a green checkmark next to it, but both reviewers have yellow cirles indicating that their reviews are pending. I don't understand.

image

image

**Comment by aaron-kaplan** [comment]
Oh, it says review "is not required to merge."

**Pull request merged**
